// app/src/pages/AnalysisDetail.tsx
import { Link, useParams } from "react-router-dom";
import { useAnalysis } from "../hooks/useAnalysis";
import { analysisStatusPresentation } from "../lib/statusPresentation";
import { CapabilityRunGrid, TestRunGrid } from "../components/RunCards";
import { Stepper } from "../components/Stepper";
import { StatusChip } from "../components/StatusChip";
import { Timeline } from "../components/Timeline";
import { IconArrowRight, IconWarning } from "../components/icons";

export function AnalysisDetail() {
  const { id } = useParams<{ id: string }>();
  const { data: analysis, isLoading, isError, error } = useAnalysis(id);

  if (isLoading) {
    return (
      <section className="view">
        <div className="state-block">
          <div className="spinner" />
          <span>Loading analysis…</span>
        </div>
      </section>
    );
  }

  if (isError || !analysis) {
    return (
      <section className="view">
        <div className="error-banner">
          <IconWarning />
          <div>Couldn't load this analysis{error ? `: ${error.message}` : "."}</div>
        </div>
      </section>
    );
  }

  const presentation = analysisStatusPresentation(analysis.status);

  return (
    <section className="view">
      <div className="status-head">
        <div>
          <h1 className="company-title">{analysis.company_name}</h1>
          <div className="company-url">
            {analysis.url} · {analysis.preset_id} · <span className="mono">{analysis.id}</span>
          </div>
        </div>
        <StatusChip {...presentation} />
      </div>

      <Stepper status={analysis.status} progress={analysis.progress} />

      {analysis.warnings.length > 0 && (
        <div className="warn-banner">
          <IconWarning />
          <div>
            <b>
              {analysis.warnings.length} warning{analysis.warnings.length === 1 ? "" : "s"}:
            </b>{" "}
            {analysis.warnings.join(" · ")}
          </div>
        </div>
      )}

      {analysis.status === "failed" && (
        <div className="error-banner">
          <IconWarning />
          <div>
            <b>{analysis.error_code ?? "Analysis failed"}.</b> {analysis.error_message}
          </div>
        </div>
      )}

      {analysis.report_url && (
        <div className="card card-pad" style={{ marginBottom: 22, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div>
            <b>Report ready.</b> <span className="cell-muted">Findings, opportunities, and talking points.</span>
          </div>
          <Link className="btn btn-primary btn-sm" to={`/analyses/${analysis.id}/report`}>
            View report
            <IconArrowRight />
          </Link>
        </div>
      )}

      <div className="section-title">Test runs</div>
      <TestRunGrid runs={analysis.test_runs} />

      <div className="section-title">Capability agents</div>
      <CapabilityRunGrid runs={analysis.capability_runs} />

      <div className="section-title">Event timeline</div>
      <div className="card card-pad">
        <Timeline events={analysis.events} />
      </div>
    </section>
  );
}

// app/src/app/pages/analysis-detail.component.ts
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, inject, signal } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { ButtonModule } from "primeng/button";
import { CardModule } from "primeng/card";
import { MessageModule } from "primeng/message";
import type { AnalysisStatusResponse } from "../../lib/types";
import { TERMINAL_ANALYSIS_STATUSES } from "../../lib/types";
import { analysisStatusPresentation } from "../../lib/statusPresentation";
import { ApiService } from "../core/api.service";
import { CapabilityRunsComponent, TestRunsComponent } from "../shared/run-cards.component";
import { StatusChipComponent } from "../shared/status-chip.component";
import { StepperComponent } from "../shared/stepper.component";
import { TimelineComponent } from "../shared/timeline.component";
import { ErrorStateComponent } from "../ui/components/error-state.component";
import { LoadingStateComponent } from "../ui/components/loading-state.component";
import { PageHeaderComponent } from "../ui/components/page-header.component";

@Component({
  selector: "app-analysis-detail",
  imports: [ButtonModule, CardModule, MessageModule, CapabilityRunsComponent, TestRunsComponent, StatusChipComponent, StepperComponent, TimelineComponent, ErrorStateComponent, LoadingStateComponent, PageHeaderComponent],
  template: `<section class="view">
    @if (loading()) { <app-loading-state message="Loading analysis…" /> }
    @else if (error()) { <app-error-state [message]="'Could not load this analysis: ' + error()" retryLabel="Retry" (retry)="retry()" /> }
    @else if (analysis(); as item) {
      <app-page-header [title]="item.company_name" [subtitle]="item.url + ' · ' + item.preset_id + ' · ' + item.id">
        <app-status-chip [label]="presentation(item).label" [variant]="presentation(item).variant" />
      </app-page-header>
      <app-stepper [status]="item.status" [progress]="item.progress" />
      @if (item.warnings.length) { <p-message severity="warn" [text]="item.warnings.length + ' warning' + (item.warnings.length === 1 ? ': ' : 's: ') + item.warnings.join(' · ')" /> }
      @if (item.status === 'failed') { <p-message severity="error" [text]="(item.error_code || 'Analysis failed') + '. ' + (item.error_message || '')" /> }
      @if (item.report_url) { <p-card styleClass="report-ready"><div class="report-ready-content"><div><b>Report ready.</b> <span class="cell-muted">Findings, opportunities, and talking points.</span></div>
        <p-button label="View report" icon="pi pi-arrow-right" iconPos="right" size="small" (onClick)="openReport(item.id)" /></div></p-card> }
      <div class="section-title">Test runs</div><app-test-runs [runs]="item.test_runs" />
      <div class="section-title">Capability agents</div><app-capability-runs [runs]="item.capability_runs" />
      <div class="section-title">Event timeline</div><p-card><app-timeline [events]="item.events" /></p-card>
    }
  </section>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AnalysisDetailComponent implements OnInit, OnDestroy {
  readonly analysis = signal<AnalysisStatusResponse | null>(null); readonly loading = signal(true); readonly error = signal<string | null>(null);
  readonly presentation = (item: AnalysisStatusResponse) => analysisStatusPresentation(item.status);
  private readonly id = inject(ActivatedRoute).snapshot.paramMap.get("id") ?? "";
  private readonly api = inject(ApiService); private readonly router = inject(Router); private timer?: number;
  ngOnInit(): void { void this.refresh(); }
  ngOnDestroy(): void { window.clearTimeout(this.timer); }
  retry(): void { this.loading.set(true); void this.refresh(); }
  openReport(id: string): void { void this.router.navigate(["/analyses", id, "report"]); }
  private async refresh(): Promise<void> {
    try {
      const item = await this.api.fetchAnalysis(this.id); this.analysis.set(item); this.error.set(null);
      if (!(TERMINAL_ANALYSIS_STATUSES as readonly string[]).includes(item.status)) this.timer = window.setTimeout(() => void this.refresh(), 3500);
    } catch (error) { this.error.set(error instanceof Error ? error.message : "Unknown error"); }
    finally { this.loading.set(false); }
  }
}
