// app/src/pages/Report.tsx
import { useMemo, useState, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { useReport } from "../hooks/useReport";
import { ReportNotReadyError, ReportUnavailableError } from "../lib/api";
import { capabilityName } from "../lib/statusPresentation";
import type { EvidenceItem, Priority } from "../lib/types";
import { Bars, type BarDatum } from "../components/Bars";
import { FindingCard } from "../components/FindingCard";
import { IconLightbulb, IconWarning } from "../components/icons";

const PRIORITY_ORDER: Priority[] = ["critical", "high", "medium", "low", "informational"];

type Filter = "all" | Priority | "recommendation";

export function Report() {
  const { id } = useParams<{ id: string }>();
  const { data: report, isLoading, error } = useReport(id);
  const [filter, setFilter] = useState<Filter>("all");

  if (isLoading) {
    return (
      <section className="view">
        <div className="state-block">
          <div className="spinner" />
          <span>Loading report…</span>
        </div>
      </section>
    );
  }

  if (error instanceof ReportNotReadyError) {
    return (
      <section className="view">
        <div className="state-block">
          <div className="spinner" />
          <span>Report isn't ready yet — synthesis is still running.</span>
        </div>
        <Link className="btn btn-ghost btn-sm" to={`/analyses/${id}`}>
          Back to progress
        </Link>
      </section>
    );
  }

  if (error instanceof ReportUnavailableError) {
    return (
      <section className="view">
        <div className="error-banner">
          <IconWarning />
          <div>This analysis failed before producing a report.</div>
        </div>
        <Link className="btn btn-ghost btn-sm" to={`/analyses/${id}`}>
          Back to progress
        </Link>
      </section>
    );
  }

  if (error || !report) {
    return (
      <section className="view">
        <div className="error-banner">
          <IconWarning />
          <div>Couldn't load this report{error ? `: ${error.message}` : "."}</div>
        </div>
      </section>
    );
  }

  return <ReportView report={report} filter={filter} onFilterChange={setFilter} />;
}

function ReportView({
  report,
  filter,
  onFilterChange,
}: {
  report: NonNullable<ReturnType<typeof useReport>["data"]>;
  filter: Filter;
  onFilterChange: (f: Filter) => void;
}) {
  const evidenceById = useMemo(() => {
    const map = new Map<string, EvidenceItem>();
    for (const item of report.evidence) map.set(item.id, item);
    return map;
  }, [report.evidence]);

  const priorityCounts = useMemo(() => countBy(report.findings, (f) => f.priority), [report.findings]);
  const recommendationCount = report.findings.filter((f) => f.statement_type === "recommendation").length;
  const visibleFindings = report.findings.filter((f) => {
    if (filter === "all") return true;
    if (filter === "recommendation") return f.statement_type === "recommendation";
    return f.priority === filter;
  });

  const bytesBars = useMemo(() => buildBytesBars(report.evidence), [report.evidence]);
  const evidenceByNamespace = useMemo(() => groupBy(report.evidence, (item) => item.namespace), [report.evidence]);

  return (
    <section className="view">
      <div className="report-head">
        <div>
          <div className="crumb" style={{ marginBottom: 6 }}>
            Report for
          </div>
          <h1 className="company-title">{report.company_name}</h1>
        </div>
        <CoverageBadge coverage={report.coverage} />
      </div>

      <div className="card summary-card">
        <h2>Executive summary</h2>
        <p className="summary-text">{report.executive_summary}</p>
        <p className="narrative-text">{report.narrative}</p>
      </div>

      <div className="two-col">
        <div>
          <div className="section-title">Findings</div>
          <div className="filter-row">
            <FilterPill active={filter === "all"} onClick={() => onFilterChange("all")}>
              All ({report.findings.length})
            </FilterPill>
            {PRIORITY_ORDER.filter((p) => priorityCounts[p]).map((p) => (
              <FilterPill key={p} active={filter === p} onClick={() => onFilterChange(p)}>
                {capitalize(p)} ({priorityCounts[p]})
              </FilterPill>
            ))}
            {recommendationCount > 0 && (
              <FilterPill active={filter === "recommendation"} onClick={() => onFilterChange("recommendation")}>
                Recommendations ({recommendationCount})
              </FilterPill>
            )}
          </div>
          {visibleFindings.length === 0 ? (
            <div className="state-block">No findings in this category.</div>
          ) : (
            visibleFindings.map((finding) => (
              <FindingCard key={finding.id} finding={finding} evidenceById={evidenceById} />
            ))
          )}
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="card card-pad">
            <h2 className="side-card-title">Prioritized opportunities</h2>
            {report.prioritized_opportunities.length === 0 ? (
              <div className="cell-muted">No opportunities were surfaced for this run.</div>
            ) : (
              <div className="opp-list">
                {report.prioritized_opportunities.map((opp, i) => (
                  <div className="opp-item" key={opp.id}>
                    <span className="opp-num mono">{String(i + 1).padStart(2, "0")}</span>
                    <span className="opp-text">{opp.title}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {bytesBars.length > 0 && (
            <div className="card card-pad">
              <h2 className="side-card-title">Byte-weighted evidence</h2>
              <Bars data={bytesBars} />
            </div>
          )}

          <div className="card card-pad">
            <h2 className="side-card-title">Talking points</h2>
            <div className="talking-points">
              {report.talking_points.map((point, i) => (
                <div className="tp-item" key={i}>
                  <IconLightbulb />
                  <span>{point}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="section-title">Evidence appendix</div>
      <div className="card card-pad">
        {Object.entries(evidenceByNamespace).map(([namespace, items]) => (
          <details key={namespace} style={{ marginBottom: 8 }}>
            <summary style={{ cursor: "pointer", fontSize: 12.5, fontWeight: 650 }}>
              <span className="mono">{namespace}</span> · {items.length} record{items.length === 1 ? "" : "s"}
            </summary>
            <div className="evidence-list" style={{ marginTop: 8 }}>
              {items.map((item) => (
                <div className="evidence-row" key={item.id}>
                  <span className="evidence-name">{item.name}</span>
                  <span className="evidence-value">
                    {String(item.value)}
                    {item.unit ? ` ${item.unit}` : ""}
                  </span>
                </div>
              ))}
            </div>
          </details>
        ))}
      </div>

      <div className="card card-pad" style={{ marginTop: 16 }}>
        <h2 className="side-card-title">Methodology</h2>
        <p style={{ fontSize: 12.5, color: "var(--ink-secondary)", lineHeight: 1.6 }}>{report.methodology}</p>
      </div>

      <div className="meta-foot">
        <span>
          Schema <b>{report.schema_version}</b>
        </span>
        <span>
          Model <b>{report.model_id}</b>
        </span>
        <span>
          Generated <b>{new Date(report.generated_at).toLocaleString()}</b>
        </span>
      </div>
    </section>
  );
}

function CoverageBadge({ coverage }: { coverage: NonNullable<ReturnType<typeof useReport>["data"]>["coverage"] }) {
  return (
    <div className="coverage-badge">
      <div className="coverage-dots">
        {coverage.configured.map((id) => {
          let color = "var(--surface-3)";
          let title = `${capabilityName(id)} — not run`;
          if (coverage.completed.includes(id)) {
            color = "var(--good)";
            title = `${capabilityName(id)} — completed`;
          } else if (coverage.failed.includes(id)) {
            color = "var(--critical)";
            title = `${capabilityName(id)} — failed`;
          } else if (coverage.skipped.includes(id)) {
            color = "var(--surface-3)";
            title = `${capabilityName(id)} — skipped`;
          }
          return <span key={id} style={{ background: color }} title={title} />;
        })}
      </div>
      <div>
        <b>
          {coverage.completed.length} / {coverage.configured.length}
        </b>
        <div className="cell-muted">capabilities complete</div>
      </div>
    </div>
  );
}

function FilterPill({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) {
  return (
    <button className={`filter-pill ${active ? "active" : ""}`} onClick={onClick} type="button">
      {children}
    </button>
  );
}

function countBy<T, K extends string>(items: T[], keyFn: (item: T) => K): Partial<Record<K, number>> {
  const result: Partial<Record<K, number>> = {};
  for (const item of items) {
    const key = keyFn(item);
    result[key] = (result[key] ?? 0) + 1;
  }
  return result;
}

function groupBy<T>(items: T[], keyFn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of items) {
    const key = keyFn(item);
    (result[key] ??= []).push(item);
  }
  return result;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function buildBytesBars(evidence: EvidenceItem[]): BarDatum[] {
  return evidence
    .filter((item): item is EvidenceItem & { value: number } => item.namespace === "bytes" && typeof item.value === "number")
    .sort((a, b) => b.value - a.value)
    .slice(0, 5)
    .map((item) => ({
      label: humanizeEvidenceName(item.name),
      value: item.value,
      displayValue: formatBytes(item.value, item.unit),
    }));
}

function humanizeEvidenceName(name: string): string {
  return name
    .replace(/_/g, " ")
    .replace(/\bbytes\b/gi, "")
    .trim()
    .replace(/^./, (c) => c.toUpperCase()) || name;
}

function formatBytes(value: number, unit: string | null): string {
  if (unit && unit !== "bytes") return `${value} ${unit}`;
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)} MB`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)} KB`;
  return `${value} B`;
}

// app/src/app/pages/report.component.ts
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, inject, signal } from "@angular/core";
import { AccordionModule } from "primeng/accordion";
import { MessageService } from "primeng/api";
import { ButtonModule } from "primeng/button";
import { CardModule } from "primeng/card";
import { MessageModule } from "primeng/message";
import { ProgressBarModule } from "primeng/progressbar";
import { TagModule } from "primeng/tag";
import { ActivatedRoute, Router } from "@angular/router";
import type { EvidenceItem, Finding, PerformanceReport, Priority } from "../../lib/types";
import { capabilityName } from "../../lib/statusPresentation";
import { ApiService, ReportNotReadyError, ReportUnavailableError } from "../core/api.service";
import { EmptyStateComponent } from "../ui/components/empty-state.component";
import { ErrorStateComponent } from "../ui/components/error-state.component";
import { LoadingStateComponent } from "../ui/components/loading-state.component";
import { PageHeaderComponent } from "../ui/components/page-header.component";

const PRIORITIES: Priority[] = ["critical", "high", "medium", "low", "informational"];
type Filter = "all" | Priority | "recommendation";
interface BarDatum { label: string; value: number; display: string; }

@Component({
  selector: "app-report",
  imports: [AccordionModule, ButtonModule, CardModule, MessageModule, ProgressBarModule, TagModule, EmptyStateComponent, ErrorStateComponent, LoadingStateComponent, PageHeaderComponent],
  template: `<section class="view">
    @if (loading()) { <app-loading-state message="Loading report…" /> }
    @else if (notReady()) { <app-loading-state message="Report isn't ready yet — synthesis is still running." />
      <p-button label="Back to progress" icon="pi pi-arrow-left" severity="secondary" [text]="true" (onClick)="back()" /> }
    @else if (unavailable()) { <app-error-state message="This analysis failed before producing a report." />
      <p-button label="Back to progress" icon="pi pi-arrow-left" severity="secondary" [text]="true" (onClick)="back()" /> }
    @else if (error()) { <app-error-state [message]="'Could not load this report: ' + error()" retryLabel="Retry" (retry)="retry()" /> }
    @else if (report(); as item) {
      <app-page-header [title]="item.company_name" subtitle="Evidence-grounded performance report">
        <p-button label="Copy summary" icon="pi pi-copy" severity="secondary" [outlined]="true" size="small" (onClick)="copy(item.executive_summary, 'Executive summary copied')" />
      </app-page-header>

      <p-card styleClass="coverage-card"><div class="coverage-summary"><div><strong>{{ item.coverage.completed.length }} / {{ item.coverage.configured.length }}</strong>
        <span>capabilities complete</span></div><p-progressbar [value]="coveragePercent(item)" [showValue]="false" /></div>
        <div class="coverage-tags">@for (capability of item.coverage.configured; track capability) {
          <p-tag [value]="capabilityName(capability)" [severity]="coverageSeverity(item, capability)" [title]="coverageTitle(item, capability)" />
        }</div>
      </p-card>

      <p-card styleClass="summary-card"><ng-template #title>Executive summary</ng-template>
        <p class="summary-text">{{ item.executive_summary }}</p><p class="narrative-text">{{ item.narrative }}</p>
      </p-card>

      <div class="two-col"><div class="findings-column"><div class="section-title">Findings</div><div class="filter-row">
        <p-button [label]="'All (' + item.findings.length + ')'" size="small" [outlined]="filter() !== 'all'" (onClick)="filter.set('all')" />
        @for (priority of priorities; track priority) { @if (priorityCount(priority)) {
          <p-button [label]="capitalize(priority) + ' (' + priorityCount(priority) + ')'" size="small" severity="secondary" [outlined]="filter() !== priority" (onClick)="filter.set(priority)" />
        } }
        @if (recommendationCount()) { <p-button [label]="'Recommendations (' + recommendationCount() + ')'" size="small" severity="secondary" [outlined]="filter() !== 'recommendation'" (onClick)="filter.set('recommendation')" /> }
      </div>
      @if (visibleFindings().length === 0) { <app-empty-state title="No findings in this category" icon="pi pi-search" /> }
      @else { <p-accordion [multiple]="true" styleClass="findings-accordion">
        @for (finding of visibleFindings(); track finding.id) { <p-accordion-panel [value]="finding.id">
          <p-accordion-header><div class="finding-header-content"><p-tag [value]="finding.priority" [severity]="prioritySeverity(finding.priority)" />
            <span class="finding-title">{{ finding.title }}</span><p-tag [value]="finding.statement_type" severity="secondary" />
            <span class="finding-conf">{{ confidence(finding) }}%</span></div></p-accordion-header>
          <p-accordion-content><div class="finding-statement">{{ finding.statement }}</div><div class="evidence-list">
            @if (evidenceFor(finding).length === 0) { <span class="cell-muted">No evidence records resolved for this finding.</span> }
            @for (evidence of evidenceFor(finding); track evidence.id) { <div class="evidence-row"><span class="evidence-ns mono">{{ evidence.namespace }}</span>
              <span class="evidence-name">{{ evidence.name }}</span><span class="evidence-value">{{ evidence.value }}{{ evidence.unit ? ' ' + evidence.unit : '' }}</span></div> }
          </div><p-button label="Copy finding" icon="pi pi-copy" size="small" severity="secondary" [text]="true" (onClick)="copyFinding(finding)" /></p-accordion-content>
        </p-accordion-panel> }
      </p-accordion> }
      </div><div class="report-side">
        <p-card><ng-template #title>Prioritized opportunities</ng-template>
          @if (!item.prioritized_opportunities.length) { <app-empty-state title="No opportunities surfaced" icon="pi pi-check-circle" /> }
          <div class="opp-list">@for (opportunity of item.prioritized_opportunities; track opportunity.id; let index = $index) {
            <div class="opp-item"><span class="opp-num mono">{{ pad(index + 1) }}</span><span class="opp-text">{{ opportunity.title }}</span></div> }</div>
        </p-card>
        @if (bars().length) { <p-card><ng-template #title>Byte-weighted evidence</ng-template><div class="bars">
          @for (bar of bars(); track bar.label; let index = $index) { <div class="bar-row"><span class="bar-label">{{ bar.label }}</span><div class="bar-track">
            <div class="bar-fill" [style.width.%]="barWidth(bar.value)" [style.background]="seriesColor(index)"></div></div><span class="bar-value mono">{{ bar.display }}</span></div> }
        </div></p-card> }
        <p-card><ng-template #title>Talking points</ng-template><ng-template #header><div class="card-header-action"><p-button label="Copy all" icon="pi pi-copy" size="small" severity="secondary" [text]="true" (onClick)="copy(item.talking_points.join('\n'), 'Talking points copied')" /></div></ng-template>
          <div class="talking-points">@for (point of item.talking_points; track $index) { <div class="tp-item"><i class="pi pi-lightbulb"></i><span>{{ point }}</span></div> }</div>
        </p-card>
      </div></div>

      <div class="section-title">Evidence appendix</div><p-card><p-accordion [multiple]="true">
        @for (group of evidenceGroups(); track group.namespace) { <p-accordion-panel [value]="group.namespace"><p-accordion-header>
          <span class="evidence-group-header"><span class="mono">{{ group.namespace }}</span>
            <span class="evidence-record-count">{{ group.items.length }} record{{ group.items.length === 1 ? '' : 's' }}</span></span>
        </p-accordion-header><p-accordion-content><div class="evidence-list">@for (evidence of group.items; track evidence.id) {
          <div class="evidence-row"><span class="evidence-name">{{ evidence.name }}</span><span class="evidence-value">{{ evidence.value }}{{ evidence.unit ? ' ' + evidence.unit : '' }}</span></div>
        }</div></p-accordion-content></p-accordion-panel> }
      </p-accordion></p-card>
      <p-card styleClass="methodology"><ng-template #title>Methodology</ng-template><p>{{ item.methodology }}</p></p-card>
      <div class="meta-foot"><span>Schema <b>{{ item.schema_version }}</b></span><span>Model <b>{{ item.model_id }}</b></span><span>Generated <b>{{ formatDate(item.generated_at) }}</b></span></div>
    }
  </section>`,
  styles: [`.report-side{display:flex;flex-direction:column;gap:16px}.methodology{margin-top:16px}.methodology p{font-size:12.5px;color:var(--ink-secondary);line-height:1.6}.card-header-action{display:flex;justify-content:flex-end;padding:.5rem 1rem 0}`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ReportComponent implements OnInit, OnDestroy {
  readonly id = inject(ActivatedRoute).snapshot.paramMap.get("id") ?? "";
  readonly report = signal<PerformanceReport | null>(null);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly notReady = signal(false);
  readonly unavailable = signal(false);
  readonly filter = signal<Filter>("all");
  readonly priorities = PRIORITIES;
  readonly capabilityName = capabilityName;
  readonly visibleFindings = computed(() => (this.report()?.findings ?? []).filter((finding) => this.filter() === "all" || (this.filter() === "recommendation" ? finding.statement_type === "recommendation" : finding.priority === this.filter())));
  readonly recommendationCount = computed(() => (this.report()?.findings ?? []).filter((finding) => finding.statement_type === "recommendation").length);
  readonly evidenceGroups = computed(() => {
    const groups = new Map<string, EvidenceItem[]>();
    for (const item of this.report()?.evidence ?? []) groups.set(item.namespace, [...(groups.get(item.namespace) ?? []), item]);
    return [...groups].map(([namespace, items]) => ({ namespace, items }));
  });
  readonly bars = computed(() => buildBars(this.report()?.evidence ?? []));
  private readonly api = inject(ApiService);
  private readonly router = inject(Router);
  private readonly messages = inject(MessageService);
  private timer?: number;

  ngOnInit(): void { void this.load(); }
  ngOnDestroy(): void { window.clearTimeout(this.timer); }
  back(): void { void this.router.navigate(["/analyses", this.id]); }
  retry(): void { this.loading.set(true); this.error.set(null); void this.load(); }
  priorityCount(priority: Priority): number { return this.report()?.findings.filter((finding) => finding.priority === priority).length ?? 0; }
  confidence(finding: Finding): number { return Math.round(finding.confidence * 100); }
  evidenceFor(finding: Finding): EvidenceItem[] { const ids = new Set(finding.evidence_refs); return (this.report()?.evidence ?? []).filter((item) => ids.has(item.id)); }
  coveragePercent(item: PerformanceReport): number { return item.coverage.configured.length ? item.coverage.completed.length / item.coverage.configured.length * 100 : 0; }
  coverageSeverity(item: PerformanceReport, id: string): "success" | "danger" | "secondary" { return item.coverage.completed.includes(id) ? "success" : item.coverage.failed.includes(id) ? "danger" : "secondary"; }
  coverageTitle(item: PerformanceReport, id: string): string { const state = item.coverage.completed.includes(id) ? "completed" : item.coverage.failed.includes(id) ? "failed" : item.coverage.skipped.includes(id) ? "skipped" : "not run"; return `${capabilityName(id)} — ${state}`; }
  prioritySeverity(priority: Priority): "danger" | "warn" | "info" | "secondary" { return priority === "critical" || priority === "high" ? "danger" : priority === "medium" ? "warn" : priority === "informational" ? "info" : "secondary"; }
  barWidth(value: number): number { return Math.max(2, value / Math.max(1, ...this.bars().map((bar) => bar.value)) * 100); }
  seriesColor(index: number): string { return `var(--series-${index + 1})`; }
  capitalize(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1); }
  pad(value: number): string { return String(value).padStart(2, "0"); }
  formatDate(value: string): string { return new Date(value).toLocaleString(); }
  async copy(value: string, detail: string): Promise<void> { await navigator.clipboard.writeText(value); this.messages.add({ severity: "success", summary: "Copied", detail }); }
  async copyFinding(finding: Finding): Promise<void> { await this.copy(`${finding.title}\n\n${finding.statement}`, "Finding copied"); }

  private async load(): Promise<void> {
    try { this.report.set(await this.api.fetchReport(this.id)); this.notReady.set(false); this.error.set(null); }
    catch (error) {
      if (error instanceof ReportNotReadyError) { this.notReady.set(true); this.timer = window.setTimeout(() => void this.load(), 4000); }
      else if (error instanceof ReportUnavailableError) this.unavailable.set(true);
      else this.error.set(error instanceof Error ? error.message : "Unknown error");
    } finally { this.loading.set(false); }
  }
}

function buildBars(evidence: EvidenceItem[]): BarDatum[] {
  return evidence.filter((item): item is EvidenceItem & { value: number } => item.namespace === "bytes" && typeof item.value === "number")
    .sort((a, b) => b.value - a.value).slice(0, 5).map((item) => ({
      label: item.name.replace(/_/g, " ").replace(/\bbytes\b/gi, "").trim().replace(/^./, (char) => char.toUpperCase()) || item.name,
      value: item.value,
      display: item.unit && item.unit !== "bytes" ? `${item.value} ${item.unit}` : item.value >= 1_000_000 ? `${(item.value / 1_000_000).toFixed(1)} MB` : item.value >= 1_000 ? `${(item.value / 1_000).toFixed(1)} KB` : `${item.value} B`,
    }));
}
