// app/src/app/shared/stepper.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { StepperModule } from "primeng/stepper";
import { ANALYSIS_STATUS_STEPS, type AnalysisStatus } from "../../lib/types";
import { analysisStatusPresentation } from "../../lib/statusPresentation";

@Component({
  selector: "app-stepper",
  imports: [StepperModule],
  template: `
    <p-stepper [value]="currentValue()" [linear]="true" styleClass="analysis-stepper"><p-step-list>
      @for (step of steps; track step; let index = $index) { <p-step [value]="index + 1" [disabled]="index > currentIndex()">{{ label(step) }}</p-step> }
    </p-step-list></p-stepper>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StepperComponent {
  readonly status = input.required<AnalysisStatus>();
  readonly progress = input.required<Record<string, unknown>>();
  readonly steps = ANALYSIS_STATUS_STEPS;
  readonly label = (status: AnalysisStatus): string => analysisStatusPresentation(status).label;

  currentValue(): number { return this.currentIndex() + 1; }

  currentIndex(): number {
    const status = this.status();
    if (status === "completed" || status === "completed_partial") return this.steps.length - 1;
    if (status === "failed") {
      const stage = typeof this.progress()["stage"] === "string" ? this.progress()["stage"] : undefined;
      const index = stage ? this.steps.indexOf(stage as AnalysisStatus) : -1;
      return index < 0 ? 0 : index;
    }
    const index = this.steps.indexOf(status);
    return index < 0 ? 0 : index;
  }
}

// app/src/components/Stepper.tsx
import { ANALYSIS_STATUS_STEPS, type AnalysisStatus } from "../lib/types";
import { analysisStatusPresentation } from "../lib/statusPresentation";

interface StepperProps {
  status: AnalysisStatus;
  /** AnalysisStatusResponse.progress — a stage-specific object; only
   * `progress.stage` is read here, to place a `failed` analysis on the
   * step it was on when it failed. */
  progress: Record<string, unknown>;
}

export function Stepper({ status, progress }: StepperProps) {
  const currentIndex = resolveStepIndex(status, progress);

  return (
    <div className="stepper">
      {ANALYSIS_STATUS_STEPS.map((step, index) => {
        let stateClass = "";
        if (status === "failed" && index === currentIndex) stateClass = "failed";
        else if (index < currentIndex) stateClass = "done";
        else if (index === currentIndex && status !== "failed") stateClass = "current";

        return (
          <div key={step} className={`step ${stateClass}`}>
            <div className="step-line" />
            <div className="step-dot" />
            <div className="step-label">{analysisStatusPresentation(step).label}</div>
          </div>
        );
      })}
    </div>
  );
}

function resolveStepIndex(status: AnalysisStatus, progress: Record<string, unknown>): number {
  if (status === "completed" || status === "completed_partial") {
    return ANALYSIS_STATUS_STEPS.length - 1;
  }
  if (status === "failed") {
    const stage = typeof progress.stage === "string" ? progress.stage : undefined;
    const stageIndex = stage ? ANALYSIS_STATUS_STEPS.indexOf(stage as AnalysisStatus) : -1;
    return stageIndex === -1 ? 0 : stageIndex;
  }
  const index = ANALYSIS_STATUS_STEPS.indexOf(status);
  return index === -1 ? 0 : index;
}
